### ISSUE TITLE
py-colorprinting

### ISSUE THREAD

**Issue by wizwilly** [Rebamcentire/ore-miner-wrapper#1]
└─$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/w/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: base58 in /home/w/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.1.1)
**ERROR: Could not find a version that satisfies the requirement py-colorprinting (from versions: none)
ERROR: No matching distribution found for py-colorprinting**

**Comment by yujunos** [comment]
I have the same problem

**Comment by Rebamcentire** [comment]
Fixed, try the latest version.

**Comment by wizwilly** [comment]
Many thanks for the updates
